name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10

jobs:
  cargo-fmt:
    name: "cargo fmt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install Rust toolchain"
        run: rustup component add rustfmt
      - run: ./scripts/fmt.sh

  cargo-clippy:
    name: "cargo clippy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install Rust toolchain"
        run: |
          rustup component add clippy
      - uses: Swatinem/rust-cache@v2
      - run: ./scripts/clippy.sh
#
#   cargo-test:
#     name: "cargo test"
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: "Install Rust toolchain"
#         run: |
#           rustup component add clippy
#       - uses: Swatinem/rust-cache@v2
#       - run: ./scripts/test.sh
