name: Tests

on:
  pull_request:
  push:
    branches:
      - main
      - rc
  workflow_dispatch:

jobs:
  autotests:
    name: Run tests
    strategy:
      matrix:
        node: ['18']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        working-directory: test
        run: npm ci

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            edge-runtime:test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test image
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: false
          load: true
          platforms: linux/amd64
          tags: edge-runtime:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Test
        working-directory: test
        run: npm run test
